name: "Build Export Templates"
on: push

# NOTE: If your `project.godot` is at the repository root, set `PROJECT_PATH` below to ".".

env:
  GODOT_VERSION: 4.3
  PROJECT_PATH: .

jobs:
  build-export-templates:
    name: Build Android Debug
    container: ubuntu:22.04
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up SCons
      run: |
        choco install scons -y  # Install SCons using Chocolatey

    - name: Set up MinGW
      run: |
        choco install mingw -y  # Install MinGW using Chocolatey

    - name: Build Godot (Release)
      run: |
        scons -j 4 p=windows target=release tools=no bits=64
        cp bin/godot.windows.opt.64.exe templates/windows_64_release.exe
        x86_64-w64-mingw32-strip templates/windows_64_release.exe
