name: "Build Export Templates"
on: push

# NOTE: If your `project.godot` is at the repository root, set `PROJECT_PATH` below to ".".

env:
  GODOT_VERSION: 4.3
  PROJECT_PATH: .

jobs:
  build-export-templates:
    name: Build Android Debug
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clone Godot Engine Source
      run: |
        git clone https://github.com/godotengine/godot.git
        cd godot
        git checkout 4.3

    - name: Install SCons
      run: |
        python3 -m pip install scons

    - name: Install MinGW
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64
  
    - name: Build Godot (Release)
      run: |
        cd godot
        scons -j 4 p=windows target=template_release tools=no bits=64
        cp bin/godot.windows.opt.64.exe templates/windows_64_release.exe
        x86_64-w64-mingw32-strip templates/windows_64_release.exe
