name: Build Android Export Templates
on: push

jobs:
  build-android-templates:
    name: Build Android Export Templates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clone Godot Engine Source
        run: |
          git clone https://github.com/godotengine/godot.git
          cd godot
          git checkout 4.3-stable

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64 python3-pip
          python3 -m pip install scons

      - name: Set Up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set Up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          ndk-version: 23.2.8568313

      - name: Set Environment Variables
        run: |
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/23.2.8568313" >> $GITHUB_ENV
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH

      - name: Add POST_NOTIFICATIONS Permission
        run: |
          cd godot/platform/android/java
          sed -i '/<uses-permission android:name="android.permission.INTERNET" \/>/a \
          <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />' AndroidManifest.xml

      - name: Build Android Export Templates
        run: |
          cd godot
          scons -j4 platform=android target=template_debug
          scons -j4 platform=android target=template_release

      - name: Package Export Templates
        run: |
          cd godot
          mkdir -p bin/android
          cp bin/android_debug.apk bin/android/android_debug.apk
          cp bin/android_release.apk bin/android/android_release.apk
          cd bin
          zip -r android_export_templates.zip android/

      - name: Upload Export Templates
        uses: actions/upload-artifact@v4
        with:
          name: android-export-templates
          path: godot/bin/android_export_templates.zip
