name: "Build Export Templates"
on: push

# NOTE: If your `project.godot` is at the repository root, set `PROJECT_PATH` below to ".".

env:
  GODOT_VERSION: 4.3
  PROJECT_PATH: .

jobs:
  build-export-templates:
    name: Build Android Debug
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: create template
        run: |
          rm -rf templates
          mkdir -p templates
      # Install dependencies
      - name: Install Scons
        run: |
          apt-get update
          apt-get install -y \
              build-essential scons pkg-config libx11-dev libxcursor-dev \
              libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev \
              libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm
      - name: Windows Template
        run: |
          scons -j 4 p=windows target=release tools=no bits=64
          cp bin/godot.windows.opt.64.exe templates/windows_64_release.exe
          x86_64-w64-mingw32-strip templates/windows_64_release.exe
          scons -j 4 p=windows target=release_debug tools=no bits=64
          cp bin/godot.windows.opt.debug.64.exe templates/windows_64_debug.exe
          x86_64-w64-mingw32-strip templates/windows_64_debug.exe
