name: "Build Export Templates"
on: push

jobs:
  build-windows-template:
    name: Build Windows Export Template
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clone Godot Engine Source
      run: |
        git clone https://github.com/godotengine/godot.git
        cd godot
        git checkout 4.3
    
    - name: Install SCons
      run: |
        python3 -m pip install scons
    
    - name: Install MinGW
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64
        sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
    
    - name: Create Templates Directory
      run: |
        cd godot
        mkdir -p templates
    
    - name: Build Export Template Windows
      run: |
        cd godot
        scons -j 4 p=windows target=template_release tools=no bits=64
        ls -la bin/
        cp bin/godot.windows.template_release.x86_64.exe templates/windows_64_release.exe
        x86_64-w64-mingw32-strip templates/windows_64_release.exe
   
    - name: Upload Windows Template as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-template
        path: godot/templates/windows_64_release.exe

  build-linux-template:
    name: Build Linux Export Template
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clone Godot Engine Source
      run: |
        git clone https://github.com/godotengine/godot.git
        cd godot
        git checkout 4.3
    
    - name: Install SCons
      run: |
        python3 -m pip install scons
    
    - name: Create Templates Directory
      run: |
        cd godot
        mkdir -p templates
    
    - name: Install UPX
      run: sudo apt-get install -y upx

    - name: Build Export Template Linux
      run: |
        cd godot
        scons -j 4 p=x11 target=template_release tools=no bits=64
        ls -la bin/
        cp bin/godot.linuxbsd.template_release.x86_64 templates/linux_x11_64_release
        upx templates/linux_x11_64_release

    - name: Upload Linux Template as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-template
        path: godot/templates/linux_x11_64_release
