name: "Build Export Templates"
on: push

jobs:
  build-templates:
    name: Build All Export Templates
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clone Godot Engine Source
      run: |
        git clone https://github.com/godotengine/godot.git
        cd godot
        git checkout 4.3
    
    - name: Install SCons
      run: |
        python3 -m pip install scons
    
    - name: Install MinGW
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64
        sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
    
    - name: Set Up Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Install Android SDK and Tools
      run: |
        sudo apt update
        sudo apt install -y wget unzip
        mkdir -p /opt/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d /opt/android-sdk/cmdline-tools
        mv /opt/android-sdk/cmdline-tools/cmdline-tools /opt/android-sdk/cmdline-tools/latest
        rm cmdline-tools.zip
        sudo chmod -R 777 /opt/android-sdk
        yes | /opt/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        /opt/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;33.0.0" "platforms;android-33" "ndk;23.2.8568313"
    
    - name: Set Environment Variables
      run: |
        echo "ANDROID_HOME=/opt/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_NDK_ROOT=/opt/android-sdk/ndk/23.2.8568313" >> $GITHUB_ENV
        echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
    
    - name: Create Dir
      run: |
        cd godot
        mkdir -p platform/android/java/libs/armeabi
        mkdir -p platform/android/java/libs/x86
        
    - name: Build Export Android Debug
      run: |
        cd godot
        scons -j 4 p=android target=template_debug
        ls -la bin/ platform/android/java/lib/libs/debug/arm64-v8a
        cp platform/android/java/lib/libs/debug/arm64-v8a/libgodot.android.opt.debug.so platform/android/java/libs/armeabi/libgodot_android.so
        ./gradlew build
        cp platform/android/java/build/outputs/apk/java-release-unsigned.apk templates/android_debug.apk
    
    - name: Upload Android Template as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-template
        path: godot/templates/android_debug.apk
