name: "Build Export Templates"
on: push

jobs:
  build-templates:
    name: Build All Export Templates
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clone Godot Engine Source
      run: |
        git clone https://github.com/godotengine/godot.git
        cd godot
        git checkout 4.3

    - name: Install SCons
      run: |
        python3 -m pip install scons

    - name: Install Emscripten (for Web Export)
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-distutils
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        source ./emsdk_env.sh
        cd ..

    - name: Build Web Export Templates
      run: |
        cd godot
        scons -j 4 platform=web target=template_release verbose=1
        cp bin/godot.javascript.opt.debug.html godot.html
        cp bin/godot.javascript.opt.debug.js godot.js
        cp tools/html_fs/filesystem.js .
        zip javascript_debug.zip godot.html godot.js filesystem.js
        mv javascript_debug.zip templates/
    
    - name: Upload Web Export Template as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: web-template
        path: godot/templates/javascript_release.zip
