name: "Build Export Templates"
on: push

jobs:
  build-templates:
    name: Build All Export Templates
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clone Godot Engine Source
      run: |
        git clone https://github.com/godotengine/godot.git
        cd godot
        git checkout 4.3

    - name: Install SCons
      run: |
        python3 -m pip install scons

    - name: Install MinGW
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64
        sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix

    - name: Set Up Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Install Android SDK and Tools
      run: |
        sudo apt update
        sudo apt install -y wget unzip
        mkdir -p /opt/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d /opt/android-sdk/cmdline-tools
        mv /opt/android-sdk/cmdline-tools/cmdline-tools /opt/android-sdk/cmdline-tools/latest
        rm cmdline-tools.zip
        sudo chmod -R 777 /opt/android-sdk
        yes | /opt/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        /opt/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;33.0.0" "platforms;android-33" "ndk;23.2.8568313"

    - name: Set Environment Variables
      run: |
        echo "ANDROID_HOME=/opt/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_NDK_ROOT=/opt/android-sdk/ndk/23.2.8568313" >> $GITHUB_ENV
        echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

    - name: Create Dir
      run: |
        mkdir -p platform/android/java/libs/arm64-v8a

    - name: Build Export Android Debug
      run: |
        cd godot
        scons -j 4 p=android target=template_debug
        ls -la bin/
        cp bin/libgodot.android.template_debug.arm64.so platform/android/java/libs/arm64-v8a/libgodot_android.so

    - name: Build Android APK
      run: |
        cd godot/platform/android/java
        ./gradlew assembleDebug

    - name: Upload Android Template as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-template
        path: godot/platform/android/java/build/outputs/apk/debug/java-debug.apk
