name: "Build Export Templates"
on: push

# NOTE: If your `project.godot` is at the repository root, set `PROJECT_PATH` below to ".".

env:
  GODOT_VERSION: 4.3
  PROJECT_PATH: .

jobs:
  build-export-templates:
    name: Build Android Debug
    container: ubuntu:22.04
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install SCons
      run: |
        # Install SCons using pip
        python -m pip install scons

    - name: Install MinGW
      run: |
        # Download and install MinGW
        Invoke-WebRequest -Uri https://github.com/niXman/mingw-builds-binaries/releases/download/12.2.0-rt_v10-rev2/x86_64-12.2.0-release-posix-seh-msvcrt-rt_v10-rev2.7z -OutFile mingw.7z
        7z x mingw.7z -oC:\mingw
        echo "C:\mingw\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
  
    - name: Build Godot (Release)
      run: |
        scons -j 4 p=windows target=release tools=no bits=64
        cp bin/godot.windows.opt.64.exe templates/windows_64_release.exe
        x86_64-w64-mingw32-strip templates/windows_64_release.exe
